/obj/structure/closet/crate/secure/gear_loadout
	desc = "A secure gear crate."
	name = "gear crate"

/obj/structure/closet/crate/secure/gear_loadout/legion
	desc = "A secure crate with Tau Ceti Foreign Legion branding."
	name = "tcfl gear crate"
	icon_state = "tcfl_crate"

/obj/structure/closet/crate/gear_loadout/hephaestus
	desc = "A sturdy crate with Hephaestus Industries branding."
	name = "hephaestus drop crate"
	icon_state = "heph_crate"
	door_hinge_x = 0.5

/obj/structure/closet/crate/gear_loadout/zenghu
	desc = "A sturdy crate with Zeng-Hu Pharmaceuticals branding."
	name = "zeng-hu drop crate"
	icon_state = "zenghu_crate"
	door_hinge_x = 0.5

/obj/structure/closet/crate/gear_loadout/nanotrasen
	desc = "A sturdy crate with NanoTrasen Corporation branding."
	name = "nanotrasen drop crate"
	icon_state = "nanotrasen_crate"
	door_hinge_x = 0.5

/obj/structure/closet/crate/gear_loadout/einstein
	desc = "A sturdy crate with Einstein Engines branding."
	name = "einstein drop crate"
	icon_state = "einstein_crate"
	door_hinge_x = 0.5

/obj/structure/closet/crate/gear_loadout/zavodskoi
	desc = "A sturdy crate with Zavodskoi Interstellar branding."
	name = "zavodskoi interstellar drop crate"
	icon_state = "necro_crate"
	door_hinge_x = 0.5

/obj/structure/closet/crate/secure/gear_loadout/coalition/fill()
	new /obj/item/rig/gunslinger/equipped(src)
	new /obj/item/clothing/head/helmet/space/void/coalition(src)
	new /obj/item/clothing/head/helmet/space/void/coalition(src)
	new /obj/item/clothing/head/helmet/space/void/coalition(src)
	new /obj/item/clothing/head/helmet/space/void/coalition(src)
	new /obj/item/clothing/head/helmet/space/void/coalition(src)
	new /obj/item/clothing/suit/space/void/coalition(src)
	new /obj/item/clothing/suit/space/void/coalition(src)
	new /obj/item/clothing/suit/space/void/coalition(src)
	new /obj/item/clothing/suit/space/void/coalition(src)
	new /obj/item/clothing/suit/space/void/coalition(src)
	new /obj/item/gun/projectile/revolver/mateba(src)
	new /obj/item/ammo_magazine/a454(src)
	new /obj/item/ammo_magazine/a454(src)
	new /obj/item/gun/energy/retro(src)
	new /obj/item/gun/energy/retro(src)
	new /obj/item/gun/projectile/gauss(src)
	new /obj/item/gun/projectile/gauss(src)
	new /obj/item/material/knife/bayonet(src)
	new /obj/item/material/knife/bayonet(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss/emp(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss/emp(src)
	new /obj/item/storage/box/species_modkit(src)
	new /obj/item/storage/box/coalition(src)

/obj/structure/closet/crate/secure/gear_loadout/coalition_single/fill()
	new /obj/item/clothing/head/helmet/space/void/coalition(src)
	new /obj/item/clothing/suit/space/void/coalition(src)
	new /obj/item/gun/projectile/gauss(src)
	new /obj/item/material/knife/bayonet(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss/emp(src)
	new /obj/item/device/modkit/multi_species(src)
	new /obj/item/voidsuit_modkit_multi/coalition(src)

/obj/structure/closet/crate/secure/gear_loadout/eridani/fill()
	new /obj/item/clothing/under/rank/security/pmc/epmc(src)
	new /obj/item/clothing/under/rank/security/pmc/epmc(src)
	new /obj/item/clothing/under/rank/security/pmc/epmc(src)
	new /obj/item/clothing/under/rank/security/pmc/epmc(src)
	new /obj/item/clothing/under/rank/security/pmc/epmc(src)
	new /obj/item/clothing/under/rank/medical/paramedic/pmc/epmc(src)
	new /obj/item/clothing/under/rank/security/pmc/epmc/alt(src)
	new /obj/item/clothing/head/beret/corporate/pmc/epmc(src)
	new /obj/item/clothing/head/beret/corporate/pmc/epmc(src)
	new /obj/item/clothing/head/beret/corporate/pmc/epmc(src)
	new /obj/item/clothing/head/softcap/pmc/epmc(src)
	new /obj/item/clothing/head/softcap/pmc/epmc(src)
	new /obj/item/clothing/head/softcap/pmc/epmc(src)
	new /obj/item/rig/strike/equipped(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/gun/energy/gun/nuclear(src)
	new /obj/item/gun/energy/gun/nuclear(src)
	new /obj/item/gun/energy/disruptorpistol/magnum(src)
	new /obj/item/gun/energy/disruptorpistol/magnum(src)
	new /obj/item/gun/energy/net(src)
	new /obj/item/gun/projectile/automatic/x9(src)
	new /obj/item/gun/projectile/automatic/x9(src)
	new /obj/item/ammo_magazine/c45m/auto(src)
	new /obj/item/ammo_magazine/c45m/auto(src)
	new /obj/item/ammo_magazine/c45m/auto(src)
	new /obj/item/ammo_magazine/c45m/auto(src)

/obj/structure/closet/crate/secure/gear_loadout/eridani_single/fill()
	new /obj/item/clothing/under/rank/security/pmc/epmc(src)
	new /obj/item/clothing/head/beret/corporate/pmc/epmc(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/gun/energy/gun/nuclear(src)
	new /obj/item/gun/energy/disruptorpistol/magnum(src)

/obj/structure/closet/crate/secure/gear_loadout/elyra/fill()
	new /obj/item/rig/elyran/equipped(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/gun/projectile/plasma(src)
	new /obj/item/gun/projectile/plasma(src)
	new /obj/item/gun/projectile/plasma/bolter(src)
	new /obj/item/gun/projectile/plasma/bolter(src)
	new /obj/item/gun/projectile/plasma/bolter(src)
	new /obj/item/gun/projectile/plasma/bolter(src)
	new /obj/item/ammo_magazine/plasma(src)
	new /obj/item/ammo_magazine/plasma(src)
	new /obj/item/ammo_magazine/plasma(src)
	new /obj/item/ammo_magazine/plasma(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/grenade/chem_grenade/large/phoroncleaner(src)
	new /obj/item/grenade/chem_grenade/large/phoroncleaner(src)
	new /obj/item/storage/box/ipc_modkit(src)

/obj/structure/closet/crate/secure/gear_loadout/elyra_single/fill()
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/gun/projectile/plasma/bolter(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/gun/projectile/pistol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/grenade/chem_grenade/large/phoroncleaner(src)
	new /obj/item/device/modkit/ipc(src)

/obj/structure/closet/crate/secure/gear_loadout/sol/fill()
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/rig/military/equipped(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/gun/projectile/shotgun/pump/combat/sol(src)
	new /obj/item/ammo_magazine/assault_shotgun/shells(src)
	new /obj/item/gun/projectile/automatic/rifle/sol(src)
	new /obj/item/gun/projectile/automatic/rifle/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/gun/projectile/pistol/sol(src)
	new /obj/item/gun/projectile/pistol/sol(src)
	new /obj/item/gun/projectile/pistol/sol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/storage/box/sol_warlord(src)

/obj/structure/closet/crate/secure/gear_loadout/sol_single/fill()
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/gun/projectile/automatic/rifle/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/gun/projectile/pistol/sol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/voidsuit_modkit_multi/sol_warlord(src)

/obj/structure/closet/crate/secure/gear_loadout/syndicate_softsuits
	req_access = list()

/obj/structure/closet/crate/secure/gear_loadout/syndicate_softsuits/fill()
	for(var/i in 1 to 6)
		new /obj/item/clothing/head/helmet/space/syndicate/black/orange(src)
		new /obj/item/clothing/suit/space/syndicate/black/orange(src)
		new /obj/item/tank/emergency_oxygen/double(src)

/obj/structure/closet/crate/secure/gear_loadout/frontier_cowboys
	req_access = list()

/obj/structure/closet/crate/secure/gear_loadout/frontier_cowboys/fill()
	for(var/i in 1 to 6)
		var/obj/item/clothing/pants/shorts/khaki/pants = new(src)
		var/obj/item/clothing/under/dressshirt/rolled/shirt = new(src)
		var/obj/item/clothing/accessory/chaps/chaps = new(src)
		var/obj/item/clothing/accessory/suspenders/suspenders = new(src)
		var/obj/item/clothing/accessory/wcoat_rec/waistcoat = new(src)
		var/obj/item/clothing/head/cowboy/hat = new(src)

		pants.attach_accessory(null, chaps)
		waistcoat.color = COLOR_BEASTY_BROWN
		shirt.attach_accessory(null, waistcoat)
		suspenders.color = COLOR_MAROON
		pants.attach_accessory(null, suspenders)
		hat.color = COLOR_BEASTY_BROWN

		new /obj/item/clothing/shoes/cowboy(src)
		new /obj/item/clothing/gloves/fingerless(src)
		new /obj/item/clothing/accessory/holster/thigh(src)
		new /obj/item/melee/whip(src)
		new /obj/item/gun/projectile/revolver/detective(src)
		new /obj/item/gun/projectile/shotgun/pump/lever_action(src)

/obj/structure/closet/crate/secure/gear_loadout/frontier_cowboys/single/fill()
	var/obj/item/clothing/pants/shorts/khaki/pants = new(src)
	var/obj/item/clothing/under/dressshirt/rolled/shirt = new(src)
	var/obj/item/clothing/accessory/chaps/chaps = new(src)
	var/obj/item/clothing/accessory/suspenders/suspenders = new(src)
	var/obj/item/clothing/accessory/wcoat_rec/waistcoat = new(src)
	var/obj/item/clothing/head/cowboy/hat = new(src)

	pants.attach_accessory(null, chaps)
	waistcoat.color = "#78280b"
	shirt.attach_accessory(null, waistcoat)
	suspenders.color = "#521600"
	pants.attach_accessory(null, suspenders)
	hat.color = "#521600"

	new /obj/item/clothing/shoes/cowboy(src)
	new /obj/item/clothing/gloves/fingerless(src)
	new /obj/item/clothing/accessory/holster/thigh(src)
	new /obj/item/melee/whip(src)
	new /obj/item/gun/projectile/revolver/detective(src)
	new /obj/item/gun/projectile/shotgun/pump/lever_action(src)

//Megacorporate suits are used in devices and tools in the uplink
/obj/structure/closet/crate/gear_loadout/zavodskoi/fill()
	new /obj/item/clothing/head/helmet/space/void/zavodskoi(src)
	new /obj/item/clothing/suit/space/void/zavodskoi(src)
	new /obj/item/tank/oxygen/red(src)
	new /obj/item/clothing/shoes/magboots(src)

/obj/structure/closet/crate/gear_loadout/zenghu/fill()
	new /obj/item/clothing/head/helmet/space/void/zenghu(src)
	new /obj/item/clothing/suit/space/void/zenghu(src)
	new /obj/item/tank/oxygen/red(src)
	new /obj/item/clothing/shoes/magboots(src)
	new /obj/item/device/modkit/multi_species(src)

/obj/structure/closet/crate/gear_loadout/nanotrasen/suit/fill()
	new /obj/item/rig/nanotrasen(src)
	new /obj/item/voidsuit_modkit_multi/nanotrasen(src)

/obj/structure/closet/crate/gear_loadout/hephaestus/fill()
	new /obj/item/clothing/head/helmet/space/void/hephaestus(src)
	new /obj/item/clothing/suit/space/void/hephaestus(src)
	new /obj/item/tank/oxygen/red(src)
	new /obj/item/clothing/shoes/magboots(src)

/obj/structure/closet/crate/gear_loadout/einstein/suit/fill()
	new /obj/item/clothing/head/helmet/space/void/einstein(src)
	new /obj/item/clothing/suit/space/void/einstein(src)
	new /obj/item/tank/oxygen/red(src)
	new /obj/item/clothing/shoes/magboots(src)
	new /obj/item/device/modkit/multi_species(src)

/obj/structure/closet/crate/secure/gear_loadout/dominia/fill()
	new /obj/item/clothing/under/dominia/fleet(src)
	new /obj/item/clothing/under/dominia/fleet(src)
	new /obj/item/clothing/under/dominia/fleet(src)
	new /obj/item/clothing/under/dominia/fleet/armsman(src)
	new /obj/item/clothing/under/dominia/fleet/armsman(src)
	new /obj/item/clothing/under/dominia/fleet/officer(src)
	new /obj/item/clothing/head/dominia/fleet(src)
	new /obj/item/clothing/head/dominia/fleet(src)
	new /obj/item/clothing/head/dominia/fleet(src)
	new /obj/item/clothing/head/dominia/fleet/armsman(src)
	new /obj/item/clothing/head/dominia/fleet/armsman(src)
	new /obj/item/clothing/head/dominia/fleet/officer(src)
	new /obj/item/clothing/suit/storage/dominia/fleet(src)
	new /obj/item/clothing/suit/armor/carrier/dominia(src)
	new /obj/item/clothing/suit/armor/carrier/dominia(src)
	new /obj/item/clothing/suit/armor/carrier/dominia(src)
	new /obj/item/clothing/suit/armor/carrier/dominia(src)
	new /obj/item/clothing/suit/armor/carrier/dominia(src)
	new /obj/item/clothing/accessory/armor_plate/heavy/dominia(src)
	new /obj/item/clothing/accessory/armor_plate/heavy/dominia(src)
	new /obj/item/clothing/accessory/armor_plate/heavy/dominia(src)
	new /obj/item/clothing/accessory/armor_plate/heavy/dominia(src)
	new /obj/item/clothing/accessory/armor_plate/heavy/dominia(src)
	new /obj/item/clothing/head/helmet/dominia(src)
	new /obj/item/clothing/head/helmet/dominia(src)
	new /obj/item/clothing/head/helmet/dominia(src)
	new /obj/item/clothing/head/helmet/dominia(src)
	new /obj/item/clothing/head/helmet/dominia/nco(src)
	new /obj/item/rig/jinxiang/equipped(src)
	new /obj/item/clothing/head/helmet/space/void/dominia(src)
	new /obj/item/clothing/head/helmet/space/void/dominia(src)
	new /obj/item/clothing/head/helmet/space/void/dominia(src)
	new /obj/item/clothing/head/helmet/space/void/dominia(src)
	new /obj/item/clothing/head/helmet/space/void/dominia(src)
	new /obj/item/clothing/suit/space/void/dominia(src)
	new /obj/item/clothing/suit/space/void/dominia(src)
	new /obj/item/clothing/suit/space/void/dominia(src)
	new /obj/item/clothing/suit/space/void/dominia(src)
	new /obj/item/clothing/suit/space/void/dominia(src)
	new /obj/item/gun/projectile/automatic/rifle/dominia(src)
	new /obj/item/gun/projectile/automatic/rifle/dominia(src)
	new /obj/item/ammo_magazine/a556(src)
	new /obj/item/ammo_magazine/a556(src)
	new /obj/item/ammo_magazine/a556(src)
	new /obj/item/ammo_magazine/a556(src)
	new /obj/item/gun/projectile/automatic/tommygun/dom(src)
	new /obj/item/gun/projectile/automatic/tommygun/dom(src)
	new /obj/item/gun/projectile/automatic/tommygun/dom(src)
	new /obj/item/ammo_magazine/submachinemag(src)
	new /obj/item/ammo_magazine/submachinemag(src)
	new /obj/item/ammo_magazine/submachinemag(src)
	new /obj/item/ammo_magazine/submachinemag(src)
	new /obj/item/ammo_magazine/submachinemag(src)
	new /obj/item/ammo_magazine/submachinemag(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/shield/energy/dominia(src)
	new /obj/item/shield/energy/dominia(src)
	new /obj/item/shield/energy/dominia(src)
	new /obj/item/shield/energy/dominia(src)
	new /obj/item/shield/energy/dominia(src)
	new /obj/item/storage/box/dominianvoid(src)

/obj/structure/closet/crate/secure/gear_loadout/dominia/single/fill()
	new /obj/item/clothing/under/dominia/fleet(src)
	new /obj/item/clothing/under/dominia/fleet/armsman(src)
	new /obj/item/clothing/head/helmet/space/void/dominia(src)
	new /obj/item/clothing/suit/space/void/dominia(src)
	new /obj/item/gun/projectile/automatic/rifle/dominia(src)
	new /obj/item/ammo_magazine/a556(src)
	new /obj/item/ammo_magazine/a556(src)
	new /obj/item/clothing/suit/armor/carrier/dominia(src)
	new /obj/item/clothing/accessory/armor_plate/heavy/dominia(src)
	new /obj/item/clothing/head/helmet/dominia(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/shield/energy/dominia(src)
	new /obj/item/voidsuit_modkit/dominianvoid(src)

/obj/structure/closet/crate/secure/gear_loadout/legion/fill()
	new /obj/item/clothing/under/legion(src)
	new /obj/item/clothing/under/legion(src)
	new /obj/item/clothing/under/legion(src)
	new /obj/item/clothing/under/legion/sentinel(src)
	new /obj/item/clothing/under/legion/sentinel(src)
	new /obj/item/clothing/under/legion/legate(src)
	new /obj/item/clothing/head/beret/legion/field(src)
	new /obj/item/clothing/head/beret/legion/field(src)
	new /obj/item/clothing/head/beret/legion/field(src)
	new /obj/item/clothing/head/beret/legion/field(src)
	new /obj/item/clothing/head/legion/legate(src)
	new /obj/item/clothing/head/helmet/legion(src)
	new /obj/item/clothing/head/helmet/legion(src)
	new /obj/item/clothing/head/helmet/legion(src)
	new /obj/item/clothing/head/helmet/legion(src)
	new /obj/item/clothing/head/helmet/legion(src)
	new /obj/item/clothing/accessory/legion(src)
	new /obj/item/clothing/accessory/legion(src)
	new /obj/item/clothing/accessory/legion(src)
	new /obj/item/clothing/accessory/legion(src)
	new /obj/item/clothing/accessory/legion/specialist(src)
	new /obj/item/clothing/accessory/legion/specialist(src)
	new /obj/item/clothing/accessory/legion/specialist(src)
	new /obj/item/rig/retro(src)
	new /obj/item/rig/retro(src)
	new /obj/item/rig/retro(src)
	new /obj/item/rig/retro(src)
	new /obj/item/rig/retro(src)
	new /obj/item/clothing/suit/storage/vest/legion(src)
	new /obj/item/clothing/suit/storage/vest/legion(src)
	new /obj/item/clothing/suit/storage/vest/legion(src)
	new /obj/item/clothing/suit/storage/vest/legion(src)
	new /obj/item/clothing/suit/storage/vest/legion(src)
	new /obj/item/storage/backpack/legion(src)
	new /obj/item/storage/backpack/legion(src)
	new /obj/item/storage/backpack/legion(src)
	new /obj/item/storage/backpack/legion(src)
	new /obj/item/storage/backpack/legion(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/shield/riot/tact/legion(src)
	new /obj/item/shield/riot/tact/legion(src)
	new /obj/item/gun/energy/blaster/revolver(src)
	new /obj/item/gun/energy/blaster/revolver(src)
	new /obj/item/gun/energy/blaster/carbine(src)
	new /obj/item/gun/energy/blaster/carbine(src)
	new /obj/item/gun/projectile/gauss(src)
	new /obj/item/gun/projectile/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss/emp(src)
	new /obj/item/ammo_magazine/gauss/emp(src)
	new /obj/item/melee/energy/sword/knife(src)
	new /obj/item/melee/energy/sword/knife(src)
	new /obj/item/melee/energy/sword/knife(src)
	new /obj/item/melee/energy/sword/knife(src)
	new /obj/item/material/twohanded/pike/flag(src)

/obj/structure/closet/crate/secure/gear_loadout/legion/single/fill()
	new /obj/item/clothing/under/legion(src)
	new /obj/item/clothing/head/beret/legion/field(src)
	new /obj/item/clothing/head/helmet/legion(src)
	new /obj/item/clothing/accessory/legion(src)
	new /obj/item/clothing/accessory/legion/specialist(src)
	new /obj/item/rig/retro(src)
	new /obj/item/clothing/suit/storage/vest/legion(src)
	new /obj/item/storage/backpack/legion(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/gun/energy/blaster/revolver(src)
	new /obj/item/gun/energy/blaster/carbine(src)
	new /obj/item/melee/energy/sword/knife(src)

/obj/structure/closet/crate/gear_loadout/einstein/fill()
	new /obj/item/rig/merc/einstein(src)
	new /obj/item/clothing/head/helmet/space/void/einstein(src)
	new /obj/item/clothing/head/helmet/space/void/einstein(src)
	new /obj/item/clothing/head/helmet/space/void/einstein(src)
	new /obj/item/clothing/head/helmet/space/void/einstein(src)
	new /obj/item/clothing/head/helmet/space/void/einstein(src)
	new /obj/item/clothing/suit/space/void/einstein(src)
	new /obj/item/clothing/suit/space/void/einstein(src)
	new /obj/item/clothing/suit/space/void/einstein(src)
	new /obj/item/clothing/suit/space/void/einstein(src)
	new /obj/item/clothing/suit/space/void/einstein(src)
	new /obj/item/clothing/under/rank/einstein(src)
	new /obj/item/clothing/under/rank/einstein(src)
	new /obj/item/clothing/under/rank/einstein(src)
	new /obj/item/clothing/under/rank/einstein(src)
	new /obj/item/clothing/under/rank/einstein(src)
	new /obj/item/gun/energy/laser/shotgun(src)
	new /obj/item/gun/energy/rifle(src)
	new /obj/item/gun/energy/rifle(src)
	new /obj/item/gun/projectile/pistol(src)
	new /obj/item/gun/projectile/pistol(src)
	new /obj/item/gun/projectile/pistol(src)
	new /obj/item/gun/projectile/pistol(src)
	new /obj/item/suppressor(src)
	new /obj/item/suppressor(src)
	new /obj/item/suppressor(src)
	new /obj/item/suppressor(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/storage/box/species_modkit(src)

/obj/structure/closet/crate/gear_loadout/einstein/single/fill()
	new /obj/item/clothing/head/helmet/space/void/einstein(src)
	new /obj/item/clothing/suit/space/void/einstein(src)
	new /obj/item/clothing/under/rank/einstein(src)
	new /obj/item/gun/energy/rifle(src)
	new /obj/item/gun/projectile/pistol(src)
	new /obj/item/suppressor(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/device/modkit/multi_species(src)

/obj/structure/closet/crate/gear_loadout/ceres/fill()
	new /obj/item/rig/bunker/nerfed/equipped(src)
	new /obj/item/clothing/head/helmet/space/void/lancer(src)
	new /obj/item/clothing/head/helmet/space/void/lancer(src)
	new /obj/item/clothing/head/helmet/space/void/lancer(src)
	new /obj/item/clothing/head/helmet/space/void/lancer(src)
	new /obj/item/clothing/suit/space/void/lancer(src)
	new /obj/item/clothing/suit/space/void/lancer(src)
	new /obj/item/clothing/suit/space/void/lancer(src)
	new /obj/item/clothing/suit/space/void/lancer(src)
	new /obj/item/clothing/under/lance(src)
	new /obj/item/clothing/under/lance(src)
	new /obj/item/clothing/under/lance(src)
	new /obj/item/clothing/under/lance(src)
	new /obj/item/clothing/accessory/holster/hip(src)
	new /obj/item/clothing/accessory/holster/hip(src)
	new /obj/item/clothing/accessory/holster/hip(src)
	new /obj/item/clothing/accessory/holster/hip(src)
	new /obj/item/gun/energy/rifle/laser(src)
	new /obj/item/gun/energy/rifle/laser(src)
	new /obj/item/gun/energy/rifle/laser(src)
	new /obj/item/gun/energy/rifle/laser(src)
	new /obj/item/gun/energy/repeater/pistol(src)
	new /obj/item/gun/energy/repeater/pistol(src)
	new /obj/item/gun/energy/repeater/pistol(src)
	new /obj/item/gun/energy/repeater/pistol(src)
	new /obj/item/gun/energy/rifle/ionrifle(src)
	new /obj/item/gun/projectile/peac(src)
	new /obj/item/ammo_casing/peac(src)
	new /obj/item/ammo_casing/peac(src)
	new /obj/item/ammo_casing/peac/he(src)
	new /obj/item/ammo_casing/peac/he(src)
	new /obj/item/recharger_backpack/high(src)
	new /obj/item/recharger_backpack/high(src)
	new /obj/item/recharger_backpack/high(src)
	new /obj/item/recharger_backpack/high(src)

/obj/structure/closet/crate/gear_loadout/ceres/single/fill()
	new /obj/item/clothing/head/helmet/space/void/lancer(src)
	new /obj/item/clothing/suit/space/void/lancer(src)
	new /obj/item/clothing/under/lance(src)
	new /obj/item/clothing/accessory/holster/hip(src)
	new /obj/item/gun/energy/rifle/laser(src)
	new /obj/item/gun/energy/repeater/pistol(src)
	new /obj/item/recharger_backpack/high(src)

/obj/structure/closet/crate/gear_loadout/nanotrasen/fill()
	new /obj/item/rig/nanotrasen(src)
	new /obj/item/rig/nanotrasen(src)
	new /obj/item/rig/nanotrasen(src)
	new /obj/item/rig/nanotrasen(src)
	new /obj/item/storage/box/nanotrasen_hardsuit(src)
	new /obj/item/gun/energy/laser/shotgun(src)
	new /obj/item/gun/energy/laser/shotgun(src)
	new /obj/item/gun/energy/rifle(src)
	new /obj/item/gun/energy/rifle(src)
	new /obj/item/gun/energy/gun(src)
	new /obj/item/gun/energy/gun(src)
	new /obj/item/gun/energy/pistol(src)
	new /obj/item/gun/energy/pistol(src)
	new /obj/item/gun/energy/pistol(src)
	new /obj/item/gun/energy/pistol(src)
	new /obj/item/shield/riot/tact(src)
	new /obj/item/shield/riot/tact(src)
	new /obj/item/shield/riot/tact(src)
	new /obj/item/shield/riot/tact(src)

/obj/structure/closet/crate/gear_loadout/nanotrasen/single/fill()
	new /obj/item/rig/nanotrasen(src)
	new /obj/item/voidsuit_modkit_multi/nanotrasen(src)
	new /obj/item/gun/energy/rifle(src)
	new /obj/item/gun/energy/pistol(src)
	new /obj/item/shield/riot/tact(src)


/obj/structure/closet/crate/secure/gear_loadout/hammertail/fill()
	var/i
	for(i=0, i<6, i++) //6 outfits
		new /obj/item/clothing/under/syndicate/hammertail(src)
	for(i=0, i<4, i++) //4 voidsuits w/helmets
		new /obj/item/clothing/head/helmet/space/void/merc(src)
		new /obj/item/clothing/suit/space/void/merc(src)
	for(i=0, i<4, i++) //4 e-swords
		new /obj/item/melee/energy/sword(src)
	for(i=0, i<4, i++) //4 heavy pistols w/spare magazines
		new /obj/item/gun/projectile/pistol/super_heavy(src)
		new /obj/item/ammo_magazine/super_heavy(src)
	for(i=0, i<4, i++) //4 tungsten slug guns w/spare magazines
		new /obj/item/gun/projectile/gauss(src)
		new /obj/item/ammo_magazine/gauss(src)
	for(i=0, i<2, i++) //2 assault rifles w/spare magazines
		new /obj/item/gun/projectile/automatic/rifle/sts35(src)
		new /obj/item/ammo_magazine/c762(src)
	new /obj/item/storage/box/species_modkit(src) //species modkits for switching on the fly
	new /obj/item/rig/merc(src) // Im pretty sure they invented this thing.

/obj/structure/closet/crate/secure/gear_loadout/hammertail/single/fill()
	new /obj/item/clothing/under/syndicate/hammertail(src) //1 outfit
	new /obj/item/melee/energy/sword(src) //1 e-sword
	new /obj/item/gun/projectile/revolver(src) //1 .357 pistol w/spare speedloader
	new /obj/item/ammo_magazine/a357(src)
	new /obj/item/gun/projectile/gauss(src) //1 tungsten slug gun w/spare magazine
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/device/modkit/multi_species(src)

/obj/structure/closet/crate/secure/gear_loadout/imperial_army/fill() // Was told the Jinxiang is only for the marines, so no rig
	new /obj/item/gun/projectile/automatic/rifle/dominia(src)
	new /obj/item/ammo_magazine/a556(src)
	new /obj/item/ammo_magazine/a556(src)
	new /obj/item/ammo_magazine/a556(src)
	new /obj/item/gun/projectile/automatic/rifle/dominia(src)
	new /obj/item/ammo_magazine/a556(src)
	new /obj/item/ammo_magazine/a556(src)
	new /obj/item/ammo_magazine/a556(src)
	new /obj/item/gun/projectile/automatic/rifle/dominia_carbine(src)
	new /obj/item/ammo_magazine/c762/dominia(src)
	new /obj/item/ammo_magazine/c762/dominia(src)
	new /obj/item/ammo_magazine/c762/dominia(src)
	new /obj/item/ammo_magazine/c762/dominia(src)
	new /obj/item/gun/projectile/automatic/rifle/dominia_lmg(src)
	new /obj/item/ammo_magazine/a556/dlmg(src)
	new /obj/item/ammo_magazine/a556/dlmg(src)
	new /obj/item/clothing/under/dominia/army(src)
	new /obj/item/clothing/under/dominia/army(src)
	new /obj/item/clothing/under/dominia/army(src)
	new /obj/item/clothing/under/dominia/army/nco(src)
	new /obj/item/clothing/accessory/dominia/nco_badge(src)
	new /obj/item/storage/backpack/dominia(src)
	new /obj/item/storage/backpack/dominia(src)
	new /obj/item/storage/backpack/dominia(src)
	new /obj/item/storage/backpack/dominia/nco(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/clothing/head/helmet/dominia(src)
	new /obj/item/clothing/head/helmet/dominia(src)
	new /obj/item/clothing/head/helmet/dominia(src)
	new /obj/item/clothing/head/helmet/dominia/nco(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/shoes/jackboots(src)

/obj/structure/closet/crate/secure/gear_loadout/imperial_army/single/fill()
	new /obj/item/gun/projectile/automatic/rifle/dominia_carbine(src)
	new /obj/item/ammo_magazine/c762/dominia(src)
	new /obj/item/ammo_magazine/c762/dominia(src)
	new /obj/item/ammo_magazine/c762/dominia(src)
	new /obj/item/ammo_magazine/c762/dominia(src)
	new /obj/item/clothing/under/dominia/army(src)
	new /obj/item/storage/backpack/dominia(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/clothing/head/helmet/dominia(src)
	new /obj/item/clothing/shoes/jackboots(src)

/obj/structure/closet/crate/secure/gear_loadout/tcaf/fill()
	new /obj/item/clothing/under/legion/tcaf(src)
	new /obj/item/clothing/under/legion/tcaf(src)
	new /obj/item/clothing/under/legion/tcaf(src)
	new /obj/item/clothing/under/legion/tcaf(src)
	new /obj/item/gun/energy/blaster/tcaf(src)
	new /obj/item/gun/energy/blaster/tcaf(src)
	new /obj/item/gun/energy/blaster/tcaf(src)
	new /obj/item/gun/energy/blaster/tcaf(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/shoes/jackboots/toeless(src)
	new /obj/item/clothing/shoes/jackboots/toeless(src)
	new /obj/item/clothing/shoes/jackboots/toeless(src)
	new /obj/item/clothing/shoes/jackboots/toeless(src)
	new /obj/item/rig/combat/legionnaire/equipped(src)
	new /obj/item/clothing/gloves/tcaf(src)
	new /obj/item/clothing/gloves/tcaf(src)
	new /obj/item/clothing/gloves/tcaf(src)
	new /obj/item/clothing/gloves/tcaf(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/clothing/suit/space/void/tcaf(src)
	new /obj/item/clothing/suit/space/void/tcaf(src)
	new /obj/item/clothing/suit/space/void/tcaf(src)
	new /obj/item/clothing/suit/space/void/tcaf(src)
	new /obj/item/clothing/head/helmet/space/void/tcaf(src)
	new /obj/item/clothing/head/helmet/space/void/tcaf(src)
	new /obj/item/clothing/head/helmet/space/void/tcaf(src)
	new /obj/item/clothing/head/helmet/space/void/tcaf(src)
	new /obj/item/clothing/suit/armor/carrier/tcaf(src)
	new /obj/item/clothing/suit/armor/carrier/tcaf(src)
	new /obj/item/clothing/suit/armor/carrier/tcaf(src)
	new /obj/item/clothing/suit/armor/carrier/tcaf(src)
	new /obj/item/clothing/head/helmet/tcaf(src)
	new /obj/item/clothing/head/helmet/tcaf(src)
	new /obj/item/clothing/head/helmet/tcaf(src)
	new /obj/item/clothing/head/helmet/tcaf(src)
	new /obj/item/clothing/head/helmet/tcaf/tcaf_visor(src)
	new /obj/item/clothing/head/helmet/tcaf/tcaf_visor(src)
	new /obj/item/clothing/head/helmet/tcaf/tcaf_visor(src)
	new /obj/item/clothing/head/helmet/tcaf/tcaf_visor(src)
	new /obj/item/material/twohanded/pike/flag(src)
	new /obj/item/clothing/accessory/tcaf_prefect_pauldron(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/gun/energy/blaster/revolver(src)
	new /obj/item/gun/energy/blaster/revolver(src)
	new /obj/item/gun/energy/blaster/revolver(src)
	new /obj/item/gun/energy/blaster/revolver(src)
	new /obj/item/clothing/accessory/holster/hip(src)
	new /obj/item/clothing/accessory/holster/hip(src)
	new /obj/item/clothing/accessory/holster/hip(src)
	new /obj/item/clothing/accessory/holster/hip(src)
	new /obj/item/melee/energy/sword/knife(src)
	new /obj/item/melee/energy/sword/knife(src)
	new /obj/item/melee/energy/sword/knife(src)
	new /obj/item/melee/energy/sword/knife(src)
	new /obj/item/storage/backpack/tcaf(src)
	new /obj/item/storage/backpack/tcaf(src)
	new /obj/item/storage/backpack/tcaf(src)
	new /obj/item/storage/backpack/tcaf(src)
	new /obj/item/storage/backpack/tcaf(src)
	new /obj/item/storage/box/species_modkit(src)

/obj/structure/closet/crate/secure/gear_loadout/tcaf/single/fill()
	new /obj/item/clothing/under/legion/tcaf(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/shoes/jackboots/toeless(src)
	new /obj/item/clothing/suit/space/void/tcaf(src)
	new /obj/item/clothing/head/helmet/space/void/tcaf(src)
	new /obj/item/clothing/gloves/tcaf(src)
	new /obj/item/melee/energy/sword/knife(src)
	new /obj/item/storage/backpack/tcaf(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/gun/energy/blaster/revolver(src)
	new /obj/item/clothing/accessory/holster/hip(src)
	new /obj/item/clothing/suit/armor/carrier/tcaf(src)
	new /obj/item/clothing/head/helmet/tcaf(src)
	new /obj/item/clothing/head/helmet/tcaf/tcaf_visor(src)
	new /obj/item/gun/energy/blaster/tcaf(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/device/modkit/multi_species(src)

/obj/structure/closet/crate/secure/gear_loadout/exclusionist/fill()
	new /obj/item/clothing/under/gearharness(src)
	new /obj/item/clothing/under/gearharness(src)
	new /obj/item/clothing/under/gearharness(src)
	new /obj/item/clothing/under/gearharness(src)
	new /obj/item/clothing/under/gearharness(src)
	new /obj/item/clothing/suit/armor/exclusionist(src)
	new /obj/item/clothing/suit/armor/exclusionist(src)
	new /obj/item/clothing/suit/armor/exclusionist(src)
	new /obj/item/clothing/suit/armor/exclusionist(src)
	new /obj/item/clothing/suit/armor/exclusionist(src)
	new /obj/item/clothing/mask/exclusionist(src)
	new /obj/item/clothing/mask/exclusionist(src)
	new /obj/item/clothing/mask/exclusionist(src)
	new /obj/item/clothing/mask/exclusionist(src)
	new /obj/item/clothing/mask/exclusionist(src)
	new /obj/item/clothing/ears/antenna/trinary_halo/exclusionist(src)
	new /obj/item/clothing/ears/antenna/trinary_halo/exclusionist(src)
	new /obj/item/clothing/ears/antenna/trinary_halo/exclusionist(src)
	new /obj/item/clothing/ears/antenna/trinary_halo/exclusionist(src)
	new /obj/item/clothing/ears/antenna/trinary_halo/exclusionist(src)
	new /obj/item/melee/chainsword(src)
	new /obj/item/melee/chainsword(src)
	new /obj/item/melee/chainsword(src)
	new /obj/item/melee/chainsword(src)

/obj/structure/closet/crate/secure/gear_loadout/exclusionist/single/fill()
	new /obj/item/clothing/under/gearharness(src)
	new /obj/item/clothing/suit/armor/exclusionist(src)
	new /obj/item/clothing/mask/exclusionist(src)
	new /obj/item/clothing/ears/antenna/trinary_halo/exclusionist(src)
	new /obj/item/melee/chainsword(src)

/obj/structure/closet/crate/secure/gear_loadout/hoplan/fill()
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/under/goldendeep/hoplan(src)
	new /obj/item/clothing/under/goldendeep/hoplan(src)
	new /obj/item/clothing/under/goldendeep/hoplan(src)
	new /obj/item/clothing/under/goldendeep/hoplan(src)
	new /obj/item/clothing/accessory/leg_guard/hoplan/skirt(src)
	new /obj/item/clothing/accessory/leg_guard/hoplan/skirt(src)
	new /obj/item/clothing/suit/armor/carrier/hoplan(src)
	new /obj/item/clothing/suit/armor/carrier/hoplan(src)
	new /obj/item/clothing/suit/armor/carrier/hoplan(src)
	new /obj/item/clothing/suit/armor/carrier/hoplan(src)
	new /obj/item/clothing/head/helmet/hoplan(src)
	new /obj/item/clothing/head/helmet/hoplan(src)
	new /obj/item/clothing/head/helmet/hoplan(src)
	new /obj/item/clothing/head/helmet/hoplan(src)
	new /obj/item/clothing/head/goldendeep/hoplan(src)
	new /obj/item/clothing/head/goldendeep/hoplan(src)
	new /obj/item/clothing/head/goldendeep/hoplan(src)
	new /obj/item/clothing/head/goldendeep/hoplan(src)
	new /obj/item/clothing/accessory/holster/hip/brown(src)
	new /obj/item/clothing/accessory/holster/hip/brown(src)
	new /obj/item/clothing/accessory/holster/hip/brown(src)
	new /obj/item/clothing/accessory/holster/hip/brown(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/storage/backpack/rucksack/tan(src)
	new /obj/item/storage/backpack/rucksack/tan(src)
	new /obj/item/storage/backpack/rucksack/tan(src)
	new /obj/item/storage/backpack/rucksack/tan(src)
	new /obj/item/gun/energy/rifle/laser(src)
	new /obj/item/gun/energy/rifle/laser(src)
	new /obj/item/gun/projectile/automatic/rifle/dnac(src)
	new /obj/item/ammo_magazine/a65(src)
	new /obj/item/ammo_magazine/a65(src)
	new /obj/item/ammo_magazine/a65(src)
	new /obj/item/ammo_magazine/a65(src)
	new /obj/item/gun/projectile/automatic/rifle/shotgun/xanan(src)
	new /obj/item/ammo_magazine/xanan_shotgun/shells(src)
	new /obj/item/ammo_magazine/xanan_shotgun/shells(src)
	new /obj/item/ammo_magazine/xanan_shotgun/slugs(src)
	new /obj/item/ammo_magazine/xanan_shotgun/slugs(src)
	new /obj/item/ammo_magazine/xanan_shotgun/incendiary(src)
	new /obj/item/gun/projectile/pistol/sol/konyang(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/gun/projectile/pistol/sol/konyang(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/gun/projectile/xanupistol(src)
	new /obj/item/ammo_magazine/c46m(src)
	new /obj/item/ammo_magazine/c46m(src)
	new /obj/item/gun/projectile/xanupistol(src)
	new /obj/item/ammo_magazine/c46m(src)
	new /obj/item/ammo_magazine/c46m(src)
	new /obj/item/stack/nanopaste/surge(src)
	new /obj/item/stack/nanopaste/surge(src)
	new /obj/item/stack/nanopaste/surge(src)
	new /obj/item/stack/nanopaste/surge(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/shield/energy(src)
	new /obj/item/shield/energy(src)
	new /obj/item/melee/energy/glaive(src)
	new /obj/item/melee/energy/glaive(src)
	new /obj/item/melee/energy/axe(src)
	new /obj/item/melee/energy/axe(src)
	new /obj/item/clothing/head/helmet/space/void/golden_deep/hoplan(src)
	new /obj/item/clothing/head/helmet/space/void/golden_deep/hoplan(src)
	new /obj/item/clothing/head/helmet/space/void/golden_deep/hoplan(src)
	new /obj/item/clothing/head/helmet/space/void/golden_deep/hoplan(src)
	new /obj/item/clothing/suit/space/void/golden_deep/hoplan(src)
	new /obj/item/clothing/suit/space/void/golden_deep/hoplan(src)
	new /obj/item/clothing/suit/space/void/golden_deep/hoplan(src)
	new /obj/item/clothing/suit/space/void/golden_deep/hoplan(src)
	new /obj/item/clothing/shoes/magboots(src)
	new /obj/item/clothing/shoes/magboots(src)
	new /obj/item/clothing/shoes/magboots(src)
	new /obj/item/clothing/shoes/magboots(src)
	new /obj/item/device/suit_cooling_unit(src)
	new /obj/item/device/suit_cooling_unit(src)
	new /obj/item/device/suit_cooling_unit(src)
	new /obj/item/device/suit_cooling_unit(src)

/obj/structure/closet/crate/secure/gear_loadout/hoplan/single/fill()
	new /obj/item/clothing/shoes/jackboots(src)
	new /obj/item/clothing/under/goldendeep/hoplan(src)
	new /obj/item/clothing/accessory/leg_guard/hoplan/skirt(src)
	new /obj/item/clothing/suit/armor/carrier/hoplan(src)
	new /obj/item/clothing/head/helmet/hoplan(src)
	new /obj/item/clothing/head/goldendeep/hoplan(src)
	new /obj/item/clothing/accessory/holster/hip/brown(src)
	new /obj/item/storage/belt/military(src)
	new /obj/item/storage/backpack/rucksack/tan(src)
	new /obj/item/gun/projectile/automatic/rifle/dnac(src)
	new /obj/item/ammo_magazine/a65(src)
	new /obj/item/ammo_magazine/a65(src)
	new /obj/item/ammo_magazine/a65(src)
	new /obj/item/ammo_magazine/a65(src)
	new /obj/item/gun/projectile/pistol/sol/konyang(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/stack/nanopaste/surge(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/melee/energy/glaive(src)
	new /obj/item/clothing/head/helmet/space/void/golden_deep/hoplan(src)
	new /obj/item/clothing/suit/space/void/golden_deep/hoplan(src)
	new /obj/item/clothing/shoes/magboots(src)
	new /obj/item/device/suit_cooling_unit(src)

//ninja stuff
/obj/structure/closet/crate/secure/gear_loadout/ninja
	var/associated_hardsuit = /obj/item/rig/light/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/fill()
	new associated_hardsuit(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/stealth/fill()
	..()
	new /obj/item/gun/projectile/pistol(src)
	new /obj/item/suppressor(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/sol
	associated_hardsuit = /obj/item/rig/military/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/sol/fill()
	..()
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/pistol/sol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/gunslinger
	associated_hardsuit = /obj/item/rig/gunslinger/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/gunslinger/fill()
	..()
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/revolver/detective(src)
	new /obj/item/ammo_magazine/c38(src)
	new /obj/item/ammo_magazine/c38(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/breacher/fill()
	..()
	new /obj/item/gun/energy/pistol/hegemony(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/tesla/fill()
	..()
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/pistol/adhomai(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/strike
	associated_hardsuit = /obj/item/rig/strike/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/strike/fill()
	..()
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/automatic/x9(src)
	new /obj/item/ammo_magazine/c45m/auto(src)
	new /obj/item/ammo_magazine/c45m/auto(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/jinxiang
	associated_hardsuit = /obj/item/rig/jinxiang/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/jinxiang/fill()
	..()
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/shield/energy/dominia(src)
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/tanto(src)
	new /obj/item/ammo_magazine/mc10mm(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/elyra
	associated_hardsuit = /obj/item/rig/elyran/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/elyra/fill()
	..()
	new /obj/item/gun/projectile/plasma(src)
	new /obj/item/ammo_magazine/plasma(src)
	new /obj/item/ammo_magazine/plasma(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/hacker
	associated_hardsuit = /obj/item/rig/light/hacker/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/hacker/fill()
	..()
	new /obj/item/gun/energy/xray(src)
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/energy/crossbow/largecrossbow(src)
	new /obj/item/melee/energy/sword/red(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/frontier
	associated_hardsuit = /obj/item/rig/light/offworlder/frontier/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/frontier/fill()
	..()
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/pistol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/crimson
	associated_hardsuit = /obj/item/rig/merc/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/crimson/fill()
	..()
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/revolver(src)
	new /obj/item/ammo_magazine/a357(src)
	new /obj/item/ammo_magazine/a357(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/rhino
	associated_hardsuit = /obj/item/rig/merc/distress/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/rhino/fill()
	..()
	new /obj/item/gun/projectile/automatic/rifle/sts35(src)
	new /obj/item/ammo_magazine/c762(src)
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/pistol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/einstein
	associated_hardsuit = /obj/item/rig/merc/einstein/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/einstein/fill()
	..()
	new /obj/item/clothing/under/rank/einstein(src)
	new /obj/item/clothing/accessory/holster/hip(src)
	new /obj/item/gun/energy/rifle(src)
	new /obj/item/gun/projectile/pistol(src)
	new /obj/item/suppressor(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/bunker
	associated_hardsuit = /obj/item/rig/bunker/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/bunker/fill()
	..()
	new /obj/item/clothing/under/lance(src)
	new /obj/item/clothing/accessory/holster/hip(src)
	new /obj/item/gun/energy/rifle/laser(src)
	new /obj/item/gun/projectile/pistol/super_heavy(src)
	new /obj/item/ammo_magazine/super_heavy(src)
	new /obj/item/ammo_magazine/super_heavy(src)
